3.1.1 ベクトルの定義

###### vectorMatrix1.py

In [3]:
import numpy as np

# 二行一列
w = np.array([[5.0], [3.0]])

# 一行二列
x = np.array([1.0, 5.0])
              
# すべての要素が0/１の一行五列のベクトル
zeros = np.zeros([1, 5])
ones = np.ones([1,5])

# 一様分布　一行五列の乱数
uniform = np.random.rand(1, 5)

# 正規分布　一行五列の乱数
normal = np.random.normal(size=[1, 5])

# 標準出力

print(f"ベクトルw) 形:{w.shape}, 型{w.dtype}\n{w}\n")
print(f"ベクトルx) 形:{x.shape}, 型{x.dtype}\n{x}\n")
print(f"ベクトルzeros) 形:{zeros.shape}, 型{zeros.dtype}\n{zeros}\n")
print(f"ベクトルones) 形:{ones.shape}, 型{ones.dtype}\n{ones}\n")
print(f"ベクトルuniform) 形:{uniform.shape}, 型{uniform.dtype}\n{uniform}\n")
print(f"ベクトルnormal) 形:{normal.shape}, 型{normal.dtype}\n{normal}\n")


ベクトルw) 形:(2, 1), 型float64
[[5.]
 [3.]]

ベクトルx) 形:(2,), 型float64
[1. 5.]

ベクトルzeros) 形:(1, 5), 型float64
[[0. 0. 0. 0. 0.]]

ベクトルones) 形:(1, 5), 型float64
[[1. 1. 1. 1. 1.]]

ベクトルuniform) 形:(1, 5), 型float64
[[0.45491535 0.46005621 0.11415046 0.31123291 0.76198702]]

ベクトルnormal) 形:(1, 5), 型float64
[[ 0.6338789   0.20835844  1.57806757 -0.07404864  0.48053125]]



3.1.2 ベクトルの内積

行ベクトル$\boldsymbol{x}$と列ベクトル$\boldsymbol{w}$の内積
$$\boldsymbol{xw}=
\begin{pmatrix}x_1,x_2\end{pmatrix} \begin{pmatrix}w_1\\w_2\end{pmatrix}
= x_1w_1 + x_2w_2
\\
= \|\boldsymbol{x}\| \|\boldsymbol{w}\| cos\theta
$$

L2ノルム：同じベクトル同士の内積の平方根
$$
\|\boldsymbol{w}\|=\sqrt{\boldsymbol{w}^{T}\boldsymbol{w}}
= \sqrt{w_1^{2}+w_2^{2}}
$$

##### vectorMatrix2.py

In [9]:
import numpy as np

# 二行一列
w = np.array([[5.0], [3.0]])

# 一行二列
x = np.array([[1.0, 5.0]])

# 内積
wx = np.matmul(x,w)

# ノルム
ww = np.matmul(w.T, w)

# 標準出力
print(f"xとwの内積)　形:{wx.shape}, 型:{wx.dtype}\n{wx}\n")
print(f"wのノルム)　形:{ww.shape}, 型:{ww.dtype}\n{ww}\n")

xとwの内積)　形:(1, 1), 型:float64
[[20.]]

wのノルム)　形:(1, 1), 型:float64
[[34.]]



3.1.8 行列の階数

##### 行列のランク
行列の行、列ベクトルの中で線形独立なベクトルの数


##### 線形独立性
二つの相異なる非ゼロのベクトル$\boldsymbol{v_1}$と$\boldsymbol{v_2}$が次の式を満たす。
$$
\gamma_1 = \gamma_2 
\Leftrightarrow
\gamma_1 \boldsymbol{v_1} + \gamma_2 \boldsymbol{v_2} = \boldsymbol{0}
$$

$$
\boldsymbol{A} = 
\begin{pmatrix} 6 & 2 \\ 2 & 5
\end{pmatrix}
$$
如何なる$\gamma_1$と$\gamma_2$の組み合わせにおいても線形結合を$\boldsymbol{0}$にできないため、
$rank(\boldsymbol{A}) = 0$

##### 特異行列
- ランク落ちする行列<br>
- 逆行列が存在しない

###### vectorMatrix5.py

In [11]:
import numpy as np

# 二行二列の行列
A = np.array([[6.0, 2.0], [2.0, 5.0] ])
B = np.array([[6.0, 3.0], [2.0, 1.0] ])

# ランクの計算
rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)

# 逆行列の導出
if rankA == len(A):
    invA = np.linalg.inv(A)
    print(f"行列A) rank:{rankA}\n 逆行列:\n {invA}\n")
else:
    print(f"行列A) rank:{rankA}\n 特異行列\n")


if rankB == len(B):
    invB = np.linalg.inv(B)
    print(f"行列B) rank:{rankB}\n 逆行列:\n {invB}\n")
else:
    print(f"行列B) rank:{rankB}\n 特異行列\n")


行列A) rank:2
 逆行列:
 [[ 0.19230769 -0.07692308]
 [-0.07692308  0.23076923]]

行列B) rank:1
 特異行列



3.1.11 固有値

固有ベクトル
- 任意の行列に対し、拡大または縮小のみが作用されるベクトル
- 拡大、縮尺率を固有値
例）固有ベクトル$\boldsymbol{v} = \begin{pmatrix} \frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}} \end{pmatrix}^{T}$に行列$\boldsymbol{A}$を作用させる
$$
\boldsymbol{v'} =
\boldsymbol{Av} =
\begin{pmatrix}
3 & 2 \\ 4 & 1
\end{pmatrix}
\begin{pmatrix}
\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}
} \end{pmatrix}
=
5
\begin{pmatrix}
\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}
} \end{pmatrix}
=5\boldsymbol{v}
$$

固有値問題
- 行列$\boldsymbol{A}$と固有ベクトル$\boldsymbol{v}$の間には以下の関係が成り立つ
$$
\boldsymbol{Av} = \boldsymbol{\lambda v} \\
\boldsymbol{v} \neq \boldsymbol{0}, \; \| \boldsymbol{v} \| = 1
$$

3.1.2. 固有値問題の解法

$$
\boldsymbol{Av} - \lambda\boldsymbol{v} = 0 \\
(\boldsymbol{A} - \lambda\boldsymbol{I})\boldsymbol{v} = 0
$$
- 手順1 $det(\boldsymbol{A} - \lambda\boldsymbol{I})=0$を満たす固有値$\lambda$を求める
- 手順2 固有値$\lambda$を用いて、固有値問題をを満たす固有ベクトル$\boldsymbol{v}$を求める

例）
$$
det(\boldsymbol{A} - \lambda \boldsymbol{I})
= det
\begin{pmatrix}
\begin{pmatrix}
3 & 2 \\ 4 & 1
\end{pmatrix}
-
\begin{pmatrix}
\lambda & 0 \\ 0 & \lambda
\end{pmatrix}
\end{pmatrix}
= 0 \\
\rightarrow
(3-\lambda)(1-\lambda)-8 = 0 \\
\rightarrow
\lambda = 5, -1
$$
次に固有ベクトルを求める.
固有値$\lambda=5$とすると
$$
det(\boldsymbol{A} - \lambda \boldsymbol{I})\boldsymbol{v} =
\begin{pmatrix}
-2v_{11} + 2v_{21} \\ 4v_{11} -4v_{11}
\end{pmatrix}
= 0 \\
\rightarrow
v_{11} = v_{21} \\
$$
固有値ベクトルのノルム$\| \boldsymbol{v} \| = 1$を満たすので
$$
\|v_1\| = 
\sqrt{v_{11}^2 + v_{21}^2}=1 \\
\rightarrow
v_{11} = v_{21} = \pm\frac{1}{\sqrt{2}}
$$

同様に、固有値$\lambda=-1$とすると、
固有ベクトル$\boldsymbol{v_2} = \begin{pmatrix} \mp \frac{1}{\sqrt{5}}, \pm \frac{2}{\sqrt{5}} \end{pmatrix}$となる。

##### vectorMatrix7.py

In [2]:
import numpy as np

# 行列の定義
A = np.array([ [3,2], [4,1] ])

# 固有値問題の解の導出
L, V = np.linalg.eig(A)

# 標準出力
print(f"固有値：\n{L}")
print(f"固有ベクトル：\n{V}")

固有値：
[ 5. -1.]
固有ベクトル：
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


3.1.13 固有値と固有ベクトルの性質

- 性質1  行列$\boldsymbol{A}$が対称行列(転置しても変化しない行列)の場合、固有ベクトルは互いに正規直行し、固有ベクトルを列に持つ行列$\boldsymbol{V}$は直行行列になる
- 性質2  固有値の和は行列の対角成分の和と一致する
- 性質3  固有値の席は行列式と一致する
- 性質4  直行行列$\boldsymbol{V}$の逆行列$\boldsymbol{V}^{-1}$は転置行列$\boldsymbol{V}^{T}$と一致する

##### vectorMatrix8.py

In [4]:
import numpy as np

# 行列の定義
A = np.array([ [3,1], [1,3]])

# 固有値問題
L, V = np.linalg.eig(A)

# 標準出力
print(f"行列Aの固有値：\n{L}\n")
print(f"行列Aの固有ベクトル：\n{V}\n")
print(f"固有ベクトルの内積：\n{np.matmul(V[:,[0]].T, V[:,[1]])}\n")
print(f"固有値の和：{np.sum(L)}\n")
print(f"行列Aのトレース（対角成分の和）：{np.sum(np.diag(A))}\n")
print(f"固有値の積：{np.prod(L)}\n")
print(f"行列Aの行列式：{np.linalg.det(A):.1f}\n")
print(f"行列Vの逆行列：{np.linalg.inv(V)}\n")
print(f"行列Vの転置：{V.T}\n")

行列Aの固有値：
[4. 2.]

行列Aの固有ベクトル：
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

固有ベクトルの内積：
[[0.]]

固有値の和：6.0

行列Aのトレース（対角成分の和）：6

固有値の積：8.0

行列Aの行列式：8.0

行列Vの逆行列：[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

行列Vの転置：[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

