3.3.2 ベルヌーイ分布

##### probability1.py

In [1]:
import numpy as np

# p=6/13のベルヌーイ分布を３回試行
X1 = np.random.binomial(1,6/13,10)
X2 = np.random.binomial(1,6/13,10)
X3 = np.random.binomial(1,6/13,10)

# 標準出力
print(f"データX1:\n{X1}")
print(f"データX2:\n{X2}")
print(f"データX3:\n{X3}")

データX1:
[0 0 1 0 0 0 0 1 0 1]
データX2:
[0 1 1 0 1 1 0 0 1 1]
データX3:
[1 0 1 0 0 0 0 0 0 0]
