3.4.4 分散共分散行列

変数$xとy$の各データ点$(x_i,y_i)$からそれぞれ平均$(\bar{x},\bar{y})$を引いたベクトルを$X'$とすると、
分散共分散行列$\Sigma$を以下のように表せる
$$
X' = 
\begin{pmatrix}
x_1 - \bar{x} & y_1 - \bar{y} \\
x_2 - \bar{x} & y_2 - \bar{y} \\
\vdots & \vdots \\
x_N - \bar{x} & y_N - \bar{y} \\
\end{pmatrix} 
$$

$$
\Sigma = \frac{1}{N}X'^{T}X'
=
\begin{pmatrix}
Var(x) & Cov(x,y) \\
Cov(y,x) & Var(y)
\end{pmatrix}
$$

##### statistics2.py

In [6]:
import numpy as np

# 7行3列の行列を定義
X = np.array([[170,60,80], [167,52,93], [174,57,85], [181,70,80], [171,62,70], [171,66,95], [171,66,95], [168,54,85]])

# 列方向の分散と標準偏差を計算
vars = np.var(X, axis=0)
stds = np.var(X, axis=0)

# 分散共分散行列の計算
cov_nobias = np.cov(X.T)
cov_bias = np.cov(X.T, bias=1)

# 標準出力
print(f"データ:\n{X}\n")
print(f"分散）身長:{vars[0]:.2f}, 体重：{vars[1]:.2f}, 胸囲：{vars[2]:.2f}\n")
print(f"標準偏差）身長:{stds[0]:.2f}, 体重：{stds[1]:.2f}, 胸囲：{stds[2]:.2f}\n")

print(f"分散共分散行列 バイアスあり：\n{cov_bias}\n")
print(f"分散共分散行列 バイアスなし：\n{cov_nobias}\n")


データ:
[[170  60  80]
 [167  52  93]
 [174  57  85]
 [181  70  80]
 [171  62  70]
 [171  66  95]
 [171  66  95]
 [168  54  85]]

分散）身長:16.48, 体重：34.86, 胸囲：67.23

標準偏差）身長:16.48, 体重：34.86, 胸囲：67.23

分散共分散行列 バイアスあり：
[[16.484375 17.078125 -9.859375]
 [17.078125 34.859375 -3.328125]
 [-9.859375 -3.328125 67.234375]]

分散共分散行列 バイアスなし：
[[ 18.83928571  19.51785714 -11.26785714]
 [ 19.51785714  39.83928571  -3.80357143]
 [-11.26785714  -3.80357143  76.83928571]]



##### statistics3.py

In [7]:
import numpy as np

# 7行3列の行列を定義
X = np.array([[170,60,80], [167,52,93], [174,57,85], [181,70,80], [171,62,70], [171,66,95], [171,66,95], [168,54,85]])

# 相関行列の計算
corrcoef = np.corrcoef(X.T)

# 標準出力
print(f"データ:\n{X}\n")
print(f"相関行列:\n{corrcoef}\n")

データ:
[[170  60  80]
 [167  52  93]
 [174  57  85]
 [181  70  80]
 [171  62  70]
 [171  66  95]
 [171  66  95]
 [168  54  85]]

相関行列:
[[ 1.          0.7124332  -0.2961539 ]
 [ 0.7124332   1.         -0.06874548]
 [-0.2961539  -0.06874548  1.        ]]

